### ISSUE TITLE
Plans to implement notify_project_usage

### ISSUE THREAD

**Issue by tcooper** [XSEDE/amieclient#2]
The reference implementation for the _old_ AMIE (tarball version) includes, arguably the most common packet in AMIE, `notify_project_usage()`. This client does not appear to implement that packet. Is that intentional? Are there plans to implement the rest of the packets defined in the AMIE docs? Are missing packets there in the API but simply not implemented in this client? Without NPU (an possibly/likely others) are we are forced to use and maintain two transfer mechanisms for ful AMIE support?

**Comment by tcooper** [comment]
Email stack hid prior response related to endpoint support for POST of /usage. Questions above regarding provision of a reference implementation via the amieclient remain valid.

**Comment by sabo** [comment]
Hi @tcooper, thanks for taking a look.

Usage is handled by a separate REST API altogether. I've pushed a client and documentation for the Usage API in the add_usage branch. It'll get merged into master as soon as I've gotten a chance to test it a bit more.

**Comment by sabo** [comment]
Going to close this issue, feel free to open a new one if you have any questions
