### ISSUE TITLE
json() timestamp issue

### ISSUE THREAD

**Issue by rynge** [XSEDE/amieclient#28]
I'm running into packet_timestamp issues because (according to other places in the code) both a str or datetime object is valid. However, that assumption is not carried through everywhere. For example, calling json() twice is not working as the first time around, packet_timestamp is updated to a str, but the second time around, a datetime is expected:

https://github.com/XSEDE/amieclient/blob/18d768603050c5e5954900ab403cb0da63a5fa12/amieclient/packet/base.py#L386-L398

I also saw a similar problem somewhere in send_packet, where invalid json was generated. I'll need to dig to find this one again.

**Comment by sabo** [comment]
I'm having trouble reproducing this. I'm able to create a packet and call `pkt.json()` twice:
```
In [13]: pkt = Packet.from_dict(DEMO_JSON_PKT_1)

In [14]: pkt.json()
Out[14]: '{"DATA_TYPE": "Packet", [snipped]

In [15]: pkt.json()
Out[15]: '{"DATA_TYPE": "Packet", [snipped]
```
Can you maybe share an example that triggers the issue you're seeing?

Regarding the client's timestamp handling when a packet is created, if we're given a string as a timestamp, we convert that to a datetime object:
https://github.com/XSEDE/amieclient/blob/18d768603050c5e5954900ab403cb0da63a5fa12/amieclient/packet/base.py#L152-L161

So, after packet creation, the internal representation of the timestamp should always be a datetime. If there's anywhere we assume that the internal representation is a string, that's a bug that should be fixed, but nothing obvious came up with a quick check. 

The timestamp is exposed as a read-only property (or, at least, as much of one as python allows), so nothing should be able to change the timestamp unless it's directly modifying the underlying `_packet_timestamp` attribute:

```
In [17]: pkt.packet_timestamp = 'a bag of chips'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-0c480326a7bc> in <module>
----> 1 pkt.packet_timestamp = 'a bag of chips'

AttributeError: can't set attribute
```

In any event, if I'm not mistaken, from a client's perspective the timestamp field is read-only and set on the server side. I believe the API ignores any values it gets from client JSON, (although @ericblau please correct me if I'm wrong).

**Comment by ericblau** [comment]
You're not wrong: the AMIE API (well, the database behind it) generates all packet and transaction timestamps.  You can POST a packet that includes a timestamp value, but the API will ignore it.

**Comment by rynge** [comment]
One place I got into trouble is when generating reply packets and then trying to save then. Example:

```
>>> pkt.json()
[valid json]
>>> pkt2 = pkt.reply_packet()
>>> pkt2.json()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rynge/tmp/venv/lib/python3.9/site-packages/amieclient/packet/base.py", line 393, in json
    formatted_time = (d['header']['packet_timestamp']
AttributeError: 'NoneType' object has no attribute 'astimezone'
```

**Comment by sabo** [comment]
Right, good catch, we should just leave `packet_timestamp` in the json unset in that case. I'll push a fix
