### ISSUE TITLE
NotifyProjectCreate packet as generated by .reply_packet() on an RPC does not contain all required fields

### ISSUE THREAD

**Issue by phpHavok** [XSEDE/amieclient#7]
The [NotifyProjectCreate](https://github.com/XSEDE/amieclient/blob/main/amieclient/packet/project.py#L19-L30) packet lists these as required fields:
```
    _data_keys_required = [
        'GrantNumber',
        'PfosNumber',
        'PiOrgCode',
        'PiPersonID',
        'PiRemoteSiteLogin',
        'ProjectID',
        'ProjectTitle',
        'ResourceList',
        'ServiceUnitsAllocated',
        'StartDate'
    ]
```
The `.reply_packet()` method on a RequestProjectCreate is supposed to generate a reply packet with all fields filled in that it knows about. According to the [example code](https://github.com/XSEDE/amieclient/blob/main/examples/process_packets.py#L72-L75), the only fields that need to be added are 3:
```
        npc.ProjectID = project_id           # local project ID
        npc.PiRemoteSiteLogin = pi_login     # local login for the PI on the resource
        npc.PiPersonID = pi_person_id        # local person ID for the pi
```
However, when I call the `.reply_packet()` method and then inspect its contents through printing the `as_dict()` method on it, I see many missing fields that are required (at least required according to AMIE-XSEDE.pdf and the above `_data_keys_required` dict):
```
{'DATA_TYPE': 'packet',
 'body': {'ProposalNumber': 'EVE216259'},
 'header': {'expected_reply_list': [{'timeout': 30240,
                                     'type': 'data_project_create'}],
            'in_reply_to': 175767090,
            'local_site_name': None,
            'originating_site_name': None,
            'outgoing_flag': None,
            'packet_id': None,
            'packet_rec_id': None,
            'packet_state': None,
            'remote_site_name': None,
            'trans_rec_id': None,
            'transaction_id': None,
            'transaction_state': None},
 'type': 'notify_project_create'}
```
Is this a bug? Or is it really okay for *GrantNumber*, *PfosNumber*, etc. to not be listed in the reply packet despite the `_data_keys_required` dict and the AMIE-XSEDE.pdf file?

Thanks!

**Comment by shapiro2** [comment]
The only fields you need to fill in are the ProjectID, PiPersonID, and PiRemoteSiteLogin. The API will fill in all the others from the RPC for you.
This is documented in the amieclient/examples/process_packets.py. Look at how it constructs the NPC in reply to an RPC.

________________________________

**Comment by phpHavok** [comment]
Thanks @shapiro2 ! That was a bit confusing for us. We did see the example code as referenced above, but wasn't sure if it was a typo/error in the example given all the other information we were reading.
